### ISSUE TITLE
"Pufferfish2 performs 82.5x more random reads than bcrypt" is too good to be true (and isn't)

### ISSUE THREAD

**Issue by solardiz** [epixoip/pufferfish#7]
`README.md` currently says this about bcrypt cost 15:

```
    Performs 6,538,944 random 32-bit reads
[...]
In other words, in nearly the same duration of time, Pufferfish2 performs 82.5x more random reads than bcrypt
```

This can't possibly be true, and indeed is not. Per my math, bcrypt cost 15 performs this many random 32-bit reads:

```
(2^15*(9+512)*2+9+512+64)*16*4 = 2185269824
```

(That's during cracking computing 64-bit partial hashes. The number 64 would be 3x higher for new full hash computation. Indeed, that's an insignificant difference at cost 15.)

So in that example Pufferfish2, if its reported number of reads is correct, performs about 4x fewer reads (but those are from L2 cache and are 64-bit, making them also more costly for attacks).

The documentation should be corrected.

**Comment by solardiz** [comment]
Oh, just noticed PR #5 reports the same and partially fixes the README. Sorry for the noise. That PR must be completed and merged.

**Comment by Sc00bz** [comment]
@epixoip, this issue can be closed.
